"""
Inference utilities for microbiological growth prediction.

This module receives user input parameters, predicts microbial growth for all
available organisms, evaluates food safety at the requested storage time, and
computes the time-to-danger for each bacterium over an extended prediction horizon.

Expected input:
    params = {
        "matrixID": matrixID,
        "temperature": temperature_value,
        "time": time_in_hours,
    }

    Returns
    -------
    Dict[str, Any]
        Dictionary containing all inference outputs generated from the input
        matrix, temperature, and storage time.

        Structure
        ---------
        result = {
            "is_safe": bool,
            "bacterias": list[str],
            "final_logC": dict[str, float],
            "cooking_reco": str,
            "times": numpy.ndarray,
            "logCs": dict[str, numpy.ndarray],
            "fig": Any,
            "time_to_danger_per_bacteria": dict[str, Optional[float]],
        }

        Content
        -------
        "is_safe" : bool
            Global safety flag at the user-requested storage time.
            It is True only if the predicted concentration of every bacterium
            remains strictly below its corresponding "high" threshold defined
            in MICROORGANISM. Otherwise, it is False.

        "bacterias" : list[str]
            List of human-readable bacteria names considered to be of concern
            at the requested storage time.
            A bacterium is included in this list when its predicted final
            concentration is greater than or equal to its "raw" threshold.
            The names stored in this list correspond to the "usual_name"
            field from MICROORGANISM, not the internal OrganismID codes.

        "final_logC" : dict[str, float]
            Final predicted concentration for each bacterium at the requested
            storage time.
            Keys are OrganismID values such as "lm", "ec", "ss", or "ta".
            Values are the predicted concentrations returned by the primary
            model at the final time point.

            Example:
                {
                    "lm": 3.42,
                    "ec": 1.87,
                    "ss": 2.15,
                    "ta": 6.91,
                }

        "cooking_reco" : str
            Cooking recommendation derived from the predicted final
            concentration of total aerobic bacteria ("ta").
            Possible values are:
            - "raw"    : concentration below the "raw" threshold
            - "medium" : concentration >= "raw" and < "medium"
            - "high"   : concentration >= "medium" and < "high"
            - "unsafe" : concentration >= "high"

        "times" : numpy.ndarray
            One-dimensional array of time values used to generate the growth
            curves returned in "logCs" and displayed in "fig".
            This array spans from 0 to the user-requested storage time, with
            N_PLOT_POINTS equally spaced values.

            Example:
                array([0.0, 3.6, 7.2, ..., 360.0])

        "logCs" : dict[str, numpy.ndarray]
            Predicted growth/concentration curves for each bacterium over the
            time grid stored in "times".
            Each key is an OrganismID, and each value is a one-dimensional
            NumPy array of the same length as "times".
            Therefore, for a given bacterium:
                logCs[bacteria][i]
            is the predicted concentration at:
                times[i]

            Example:
                {
                    "lm": array([...]),
                    "ec": array([...]),
                    "ss": array([...]),
                    "ta": array([...]),
                }

        "fig" : Any
            Figure object generated by plot_predictions_over_time().
            It contains the graphical representation of predicted bacterial
            growth as a function of time.
            The exact type depends on the plotting backend used by
            plot_predictions_over_time().

        "time_to_danger_per_bacteria" : dict[str, Optional[float]]
            Estimated time at which each bacterium first reaches or exceeds
            its "high" threshold, based on predictions computed over the
            extended time horizon [0, MAX_PREDICTION_TIME].
            Keys are OrganismID values.
            Values are:
            - a float: the first dangerous time detected
            - None: if the bacterium never reaches its "high" threshold within
              the prediction horizon

            Example:
                {
                    "lm": 142.3,
                    "ec": None,
                    "ss": 87.6,
                    "ta": 36.1,
                }

        Notes
        -----
        - The keys of "final_logC", "logCs", and
          "time_to_danger_per_bacteria" are internal OrganismID codes.
        - The values in "bacterias" are human-readable names.
        - "times" and "logCs" describe the prediction over the user-requested
          storage interval.
        - "time_to_danger_per_bacteria" is computed on a longer interval,
          from 0 to MAX_PREDICTION_TIME, and may therefore indicate a danger
          time occurring after the requested storage time.
"""

from __future__ import annotations

from typing import Any, Dict, Iterable, Mapping, Optional, Union

import numpy as np

from ml_logic.sk_baseline import ClassicalModelRegressor
from interface.bacteria_information import MICROORGANISM
from . import arrhenius_parameters
from interface.graphics import plot_predictions_over_time


MAX_PREDICTION_TIME = 1000
N_PLOT_POINTS = 100
N_SHELF_LIFE_POINTS = 500

PRIMARY_PARAM_NAMES = ["Initial Value", "Lag", "Maximum Rate", "Final Value"]


def infer(params: Mapping[str, Union[str, float, int]]) -> Dict[str, Any]:
    """
    Run the full inference pipeline for microbiological growth prediction.

    The function:
    1. Validates user inputs.
    2. Retrieves Arrhenius parameters for the requested food matrix.
    3. Predicts microbial growth up to the requested storage time.
    4. Computes final concentrations at the requested time.
    5. Evaluates food safety and cooking recommendation.
    6. Computes time-to-danger for each bacterium over an extended time horizon.
    7. Generates the growth plot.

    Parameters
    ----------
    params : Mapping[str, Union[str, float, int]]
        Input parameters. Expected keys are:
        - "matrixID": food matrix identifier
        - "temperature": storage temperature
        - "time": storage duration

    Returns
    -------
    Dict[str, Any]
        Dictionary containing safety assessment, predicted concentrations,
        cooking recommendation, growth curves, figure, and time-to-danger
        per bacterium.
    """
    validated_params = _validate_inference_params(params)

    matrix_id = validated_params["matrixID"]
    temperature = validated_params["temperature"]
    requested_time = validated_params["time"]

    # Time grid for display up to user-requested storage time
    times = np.linspace(0.0, requested_time, N_PLOT_POINTS)

    # Time grid for shelf-life / time-to-danger computation
    extended_times = np.linspace(0.0, MAX_PREDICTION_TIME, N_SHELF_LIFE_POINTS)


    # Retrieve matrix-specific secondary-model parameters
    organism_secondary_params = get_arrhenius_params(
        {"matrixID": matrix_id},
        arrhenius_parameters,
    )

    # Predict growth curves up to requested time
    predictions = predict_for_all_organisms(
        temperature=temperature,
        times=times,
        organism_secondary_params=organism_secondary_params,
    )

    # Predict growth curves up to MAX_PREDICTION_TIME for time-to-danger computation
    extended_predictions = predict_for_all_organisms(
        temperature=temperature,
        times=extended_times,
        organism_secondary_params=organism_secondary_params,
    )

    # Final concentration at requested time
    final_growth = _extract_final_growth(predictions)
    final_concentration = _growth_to_concentration(final_growth)

    # Safety evaluation
    is_safe, bacterias = _evaluate_safety(final_concentration)

    # Cooking recommendation based on total aerobic bacteria ("ta")
    cooking_reco = _get_cooking_recommendation(final_concentration)

    # Time-to-danger per bacterium
    time_to_danger_per_bacteria = compute_time_to_danger_per_bacteria(
        times=extended_times,
        predicted_growth=extended_predictions,
    )

    # Plot figure
    fig = plot_predictions_over_time(
        extended_times,
        extended_predictions,
        storage_time=params.get('time')
    )

    result = {
        "is_safe": is_safe,
        "bacterias": bacterias,
        "final_logC": final_concentration,
        "cooking_reco": cooking_reco,
        "times": times,
        "logCs": predictions,
        "fig": fig,
        "time_to_danger_per_bacteria": time_to_danger_per_bacteria,
    }

    return result


def _validate_inference_params(
    params: Mapping[str, Union[str, float, int]]
) -> Dict[str, Union[str, float]]:
    """
    Validate and normalize inference input parameters.

    Parameters
    ----------
    params : Mapping[str, Union[str, float, int]]
        Raw user parameters.

    Returns
    -------
    Dict[str, Union[str, float]]
        Normalized parameters.

    Raises
    ------
    ValueError
        If required parameters are missing or invalid.
    """
    required_keys = ["matrixID", "temperature", "time"]

    for key in required_keys:
        if key not in params:
            raise ValueError(f"Missing required parameter: '{key}'")

    matrix_id = params["matrixID"]
    temperature = params["temperature"]
    time = params["time"]

    if matrix_id is None or str(matrix_id).strip() == "":
        raise ValueError("Parameter 'matrixID' must be a non-empty string")

    try:
        temperature = float(temperature)
    except (TypeError, ValueError) as exc:
        raise ValueError("Parameter 'temperature' must be numeric") from exc

    try:
        time = float(time)
    except (TypeError, ValueError) as exc:
        raise ValueError("Parameter 'time' must be numeric") from exc

    if time < 0:
        raise ValueError("Parameter 'time' must be >= 0")

    return {
        "matrixID": str(matrix_id),
        "temperature": temperature,
        "time": time,
    }


def get_arrhenius_params(
    params: Mapping[str, Any],
    arrhenius_parameters,
) -> Dict[Any, Dict[str, dict]]:
    """
    Retrieve Arrhenius parameters for a given food matrix.

    Parameters
    ----------
    params : Mapping[str, Any]
        Dictionary containing at least "matrixID".
    arrhenius_parameters : pandas.DataFrame
        DataFrame containing Arrhenius parameter dictionaries for each
        organism and primary-model parameter.

    Returns
    -------
    Dict[Any, Dict[str, dict]]
        Nested dictionary:
        {
            organism_id: {
                "Initial Value": {...},
                "Lag": {...},
                "Maximum Rate": {...},
                "Final Value": {...},
            },
            ...
        }

    Raises
    ------
    ValueError
        If matrixID is missing, unknown, or contains duplicate OrganismID rows.
    """
    matrix_id = params.get("matrixID")

    if matrix_id is None:
        raise ValueError("Parameter 'matrixID' is missing")

    df_filtered = arrhenius_parameters[
        arrhenius_parameters["MatrixID"] == matrix_id
    ]

    if df_filtered.empty:
        raise ValueError(f"MatrixID '{matrix_id}' not found in arrhenius_parameters")

    if df_filtered.duplicated(subset=["OrganismID"]).any():
        raise ValueError(f"Duplicate OrganismID entries for MatrixID '{matrix_id}'")

    cols = ["Initial Value", "Lag", "Maximum Rate", "Final Value"]

    return (
        df_filtered
        .set_index("OrganismID")[cols]
        .to_dict(orient="index")
    )


def predict_for_all_organisms(
    *,
    temperature: float,
    times: Union[np.ndarray, Iterable[float]],
    organism_secondary_params: Dict[Any, Dict[str, dict]],
) -> Dict[Any, np.ndarray]:
    """
    Predict primary-model growth curves for all organisms.

    For each organism:
    1. Predict each primary-model parameter from the secondary Arrhenius model.
    2. Override:
       - "Initial Value" with MICROORGANISM[organism_id]["initial"]
       - "Final Value" with 9.0
    3. Build the corresponding primary Baranyi model.
    4. Predict growth over the provided time grid.

    Parameters
    ----------
    temperature : float
        Storage temperature.
    times : Union[np.ndarray, Iterable[float]]
        Time values at which growth must be predicted.
    organism_secondary_params : Dict[Any, Dict[str, dict]]
        Nested dictionary of Arrhenius parameters by organism and by
        primary-model parameter.

    Returns
    -------
    Dict[Any, np.ndarray]
        Dictionary mapping each OrganismID to its predicted growth curve.

    Raises
    ------
    ValueError
        If a required set of secondary-model parameters is missing, or if the
        organism is missing from MICROORGANISM.
    """
    times = np.asarray(times, dtype=float)

    if times.ndim != 1:
        raise ValueError("'times' must be a 1D array-like object")

    predictions: Dict[Any, np.ndarray] = {}

    for organism_id, sec_params_by_primary_param in organism_secondary_params.items():
        primary_params: Dict[str, float] = {}

        for param_name in PRIMARY_PARAM_NAMES:
            if param_name not in sec_params_by_primary_param:
                raise ValueError(
                    f"Missing secondary-model parameters for OrganismID={organism_id}, "
                    f"primary parameter='{param_name}'"
                )

            secondary_model = ClassicalModelRegressor(model="arrhenius")
            secondary_model.fit([1, 2, 3], [1, 2, 3])
            secondary_model.params_ = sec_params_by_primary_param[param_name]

            pred_value = secondary_model.predict([temperature])

            if hasattr(pred_value, "shape"):
                pred_value = float(np.ravel(pred_value)[0])
            else:
                pred_value = float(pred_value)

            primary_params[param_name] = pred_value

        if organism_id not in MICROORGANISM:
            raise ValueError(f"Bacteria '{organism_id}' not found in MICROORGANISM")

        initial_value = MICROORGANISM[organism_id].get("initial")
        if initial_value is None:
            raise ValueError(f"'initial' value missing for bacteria '{organism_id}'")

        primary_params["Initial Value"] = float(initial_value)
        primary_params["Final Value"] = 9.0

        primary_model = ClassicalModelRegressor(model="baranyi")
        primary_model.fit([1, 2, 3], [1, 2, 3])
        primary_model.params_ = primary_params

        y_pred = primary_model.predict(times)
        predictions[organism_id] = np.asarray(y_pred, dtype=float)

    return predictions


def _extract_final_growth(predictions: Mapping[str, np.ndarray]) -> Dict[str, float]:
    """
    Extract the final predicted value for each bacterium.

    Parameters
    ----------
    predictions : Mapping[str, np.ndarray]
        Predicted curves by organism.

    Returns
    -------
    Dict[str, float]
        Final predicted value for each organism.
    """
    final_growth: Dict[str, float] = {}

    for bacteria, values in predictions.items():
        if values is None or len(values) == 0:
            raise ValueError(f"No prediction values for bacteria '{bacteria}'")
        final_growth[bacteria] = float(values[-1])

    return final_growth


def _growth_to_concentration(final_growth: Mapping[str, float]) -> Dict[str, float]:
    """
    Convert final predicted values into final concentrations.

    In the current implementation, predicted values are already interpreted as
    final concentrations. No initial value is added.

    Parameters
    ----------
    final_growth : Mapping[str, float]
        Final predicted values.

    Returns
    -------
    Dict[str, float]
        Final concentrations by bacterium.
    """
    final_concentration: Dict[str, float] = {}

    for bacteria, growth_value in final_growth.items():
        if bacteria not in MICROORGANISM:
            raise ValueError(f"Bacteria '{bacteria}' not found in MICROORGANISM")

        final_concentration[bacteria] = float(growth_value)

    return final_concentration


def _evaluate_safety(
    final_concentration: Mapping[str, float]
) -> tuple[bool, list[str]]:
    """
    Evaluate food safety and identify bacteria of concern.

    A food is considered safe only if all bacteria remain strictly below their
    'high' threshold.

    Bacteria are listed in the returned 'bacterias' list when their final
    concentration is greater than or equal to their 'raw' threshold.

    Parameters
    ----------
    final_concentration : Mapping[str, float]
        Final log concentrations by bacterium.

    Returns
    -------
    tuple[bool, list[str]]
        - is_safe: overall safety status
        - bacterias: list of human-readable bacteria names of concern
    """
    all_below_high = True
    bacterias: list[str] = []

    for bacteria, concentration in final_concentration.items():
        if bacteria not in MICROORGANISM:
            raise ValueError(f"Bacteria '{bacteria}' not found in MICROORGANISM")

        data = MICROORGANISM[bacteria]
        high_threshold = data.get("high")
        raw_threshold = data.get("raw")
        usual_name = data.get("usual_name")

        if high_threshold is None:
            raise ValueError(f"'high' threshold missing for bacteria '{bacteria}'")
        if raw_threshold is None:
            raise ValueError(f"'raw' threshold missing for bacteria '{bacteria}'")
        if usual_name is None:
            raise ValueError(f"'usual_name' missing for bacteria '{bacteria}'")

        if concentration >= high_threshold:
            all_below_high = False

        if concentration >= raw_threshold:
            bacterias.append(usual_name)

    return all_below_high, bacterias


def _get_cooking_recommendation(final_concentration: Mapping[str, float]) -> str:
    """
    Determine the cooking recommendation based on total aerobic bacteria ('ta').

    Rules:
    - >= high   -> 'unsafe'
    - >= medium -> 'high'
    - >= raw    -> 'medium'
    - else      -> 'raw'

    Parameters
    ----------
    final_concentration : Mapping[str, float]
        Final log concentrations by bacterium.

    Returns
    -------
    str
        Cooking recommendation level.
    """
    if "ta" not in MICROORGANISM:
        raise ValueError("Bacteria 'ta' not found in MICROORGANISM")

    ta_values = MICROORGANISM["ta"]
    ta_final_concentration = final_concentration.get("ta")

    if ta_final_concentration is None:
        raise ValueError("Final concentration for bacteria 'ta' is missing")

    if ta_final_concentration >= ta_values["high"]:
        return "unsafe"
    if ta_final_concentration >= ta_values["medium"]:
        return "high"
    if ta_final_concentration >= ta_values["raw"]:
        return "medium"
    return "raw"


def compute_time_to_danger_per_bacteria(
    *,
    times: Union[np.ndarray, Iterable[float]],
    predicted_growth: Mapping[str, np.ndarray],
) -> Dict[str, Optional[float]]:
    """
    Compute the first time at which each bacterium reaches its high threshold.

    In the current implementation, predicted values are already interpreted as
    concentrations. No initial value is added before comparison to the threshold.

    Parameters
    ----------
    times : Union[np.ndarray, Iterable[float]]
        Time grid used for prediction.
    predicted_growth : Mapping[str, np.ndarray]
        Predicted curves by organism.

    Returns
    -------
    Dict[str, Optional[float]]
        Dictionary mapping each OrganismID to:
        - the first time at which concentration >= high threshold, or
        - None if the threshold is never reached within the prediction horizon.
    """
    times = np.asarray(times, dtype=float)

    if times.ndim != 1:
        raise ValueError("'times' must be a 1D array-like object")

    time_to_danger: Dict[str, Optional[float]] = {}

    for bacteria, growth_values in predicted_growth.items():
        if bacteria not in MICROORGANISM:
            raise ValueError(f"Bacteria '{bacteria}' not found in MICROORGANISM")

        growth_values = np.asarray(growth_values, dtype=float)

        if len(growth_values) != len(times):
            raise ValueError(
                f"Length mismatch for bacteria '{bacteria}': "
                f"{len(growth_values)} predictions for {len(times)} time points"
            )

        high_threshold = MICROORGANISM[bacteria].get("high")
        if high_threshold is None:
            raise ValueError(f"'high' threshold missing for bacteria '{bacteria}'")

        danger_indices = np.where(growth_values >= float(high_threshold))[0]

        if len(danger_indices) == 0:
            time_to_danger[bacteria] = None
        else:
            time_to_danger[bacteria] = float(times[danger_indices[0]])

    return time_to_danger


def get_usual_name(keys):
    """
    Retrieve usual_name(s) from MICROORGANISM.

    Parameters
    ----------
    keys : str or list[str]
        Bacteria code or list of bacteria codes.

    Returns
    -------
    str or list[str]
        Usual name(s) corresponding to the provided key(s).

    Raises
    ------
    ValueError
        If a key does not exist or if 'usual_name' is missing.
    """
    single_input = False
    if isinstance(keys, str):
        keys = [keys]
        single_input = True

    if not isinstance(keys, (list, tuple)):
        raise TypeError("keys must be a string or a list/tuple of strings")

    usual_names = []

    for key in keys:
        if key not in MICROORGANISM:
            raise ValueError(f"Bacteria key '{key}' not found in MICROORGANISM")

        if "usual_name" not in MICROORGANISM[key]:
            raise ValueError(f"'usual_name' missing for bacteria '{key}'")

        usual_names.append(MICROORGANISM[key]["usual_name"])

    return usual_names[0] if single_input else usual_names
